name: Lint, Build, and Test

on:
  pull_request:
  push:
    branches:
      - development
      - staging
      - main

jobs:
  tests:
    name: Lint, Build, and Test
    runs-on: ubuntu-latest
    env:
      CI: true
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/app_test
    services:
      postgres:
        image: postgres:15
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_test
          NODE_ENV: test
        # Make sure the database is ready before we use it
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 21.4.0

      - name: Install packages
        run: npm ci

      - name: Setup Database
        run: npm run db:deploy

      - name: ESLint
        run: npm run lint

      - name: Build App
        run: npm run build

      - name: Run Jest Tests
        run: npm run test

      - name: Install Browsers For Playwright
        run: npx playwright install --with-deps

      - name: Run End-to-End Tests
        run: npm run test:e2e

      - name: Save test report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ./packages/get-tachus/test-results/
          retention-days: 14
